# Generated by Django 3.2.7 on 2022-01-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.AddField(
            model_name='sprice',
            name='market',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockprice.market'),
        ),
    ]
