# Generated by Django 3.2.7 on 2021-09-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'MyChild',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('mychild', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netzwerkApp.mychild')),
            ],
            options={
                'db_table': 'MyModel',
            },
        ),
    ]
